# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('init_date', models.DateTimeField(verbose_name='date created')),
                ('mod_date', models.DateTimeField(verbose_name='date last modified')),
                ('content', models.TextField()),
                ('slug', models.SlugField(default='Untitled')),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('init_date', models.DateTimeField(verbose_name='date created')),
                ('mod_date', models.DateTimeField(verbose_name='date last modified')),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(default='Untitled')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesTaking.Notebook'),
        ),
    ]
