# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notesTaking', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
