# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesTaking', '0003_notebook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='notesTaking/img/avatar'),
        ),
    ]
